### ISSUE TITLE
Suggested resource

### ISSUE THREAD

**Issue by derduher** [mrzool/bash-sensible#12]
I wanted to point out to you and perhaps anyone else to [mathiasbynes dotfiles](https://github.com/mathiasbynens/dotfiles). Its a great community maintained set of configs. It has a much larger scope than your project, however it may be a great resource for you to draw on a "sensible" set of options. Or just a place to point people to when their suggestions fall outside "sensible" defaults.

In particular: 
- [input rc](https://github.com/mathiasbynens/dotfiles/blob/master/.inputrc) and  [exports lang](https://github.com/mathiasbynens/dotfiles/blob/master/.exports) for exceptionally relevant options (some of which you already have)
- [bash prompt](https://github.com/mathiasbynens/dotfiles/blob/master/.bash_prompt) for shmancy coloring
- [bash profile](https://github.com/mathiasbynens/dotfiles/blob/master/.bash_profile) for advanced config structuring

**Comment by mrzool** [comment]
There are several good things in there and I will definitely integrate some of them in Sensible Bash. 

Thanks for sharing!

**Comment by derduher** [comment]
My pleasure :)

**Comment by mrzool** [comment]
Need to keep this open as a memo or I'll forget about it.

**Comment by mrzool** [comment]
Took `nocaseglob`, other settings are cool but a bit too personal for a default (expecially shmancy coloring).

Thanks for the suggestion!
