### ISSUE TITLE
Suggest Bash upgrade for OSX users.

### ISSUE THREAD

**Issue by afraser** [mrzool/bash-sensible#3]
You might want to update your readme.md to suggest that OSX users upgrade to bash 4.x

This worked for me (obviously need homebrew installed first).
`brew install bash;echo /usr/local/bin/bash|sudo tee -a /etc/shells;chsh -s /usr/local/bin/bash`

**Comment by ioab** [comment]
shopt was invalid command. Upgrading solved it for me. 
Thank you.

**Comment by mrzool** [comment]
That's very good to know! Thanks for the heads up.

**Comment by afraser** [comment]
`autocd` and `dirspell` specifically weren't working for me.
