### ISSUE TITLE
more readline/ inputrc options

### ISSUE THREAD

**Issue by thom-nic** [mrzool/bash-sensible#5]
I tend to use a separate `.inputrc` file but you can of course put these in `bind` commands like you're already doing from the bashrc...  Here are two of my favorites:

``` bash
# From http://www.ukuug.org/events/linux2003/papers/bash_tips/
# Incremental searching with Up and Down
"\e[A": history-search-backward
"\e[B": history-search-forward
```

e.g. so typing `ssh <up arrow>` searches through prior `ssh` commands rather than your entire command history.

**Comment by mrzool** [comment]
I also like to keep my Readline preferences in a separate `inputrc` so I have them readily available also in the other CLI applications I use—and if you notice, I use your [same exact bindings](https://github.com/mrzool/dotfiles/blob/master/inputrc) for history navigation. 

That said, key bindings are a bit too personal and outside the scope of the project, which is merely to provide a small set of agreeable defaults for everyone. Better leave this sort of things to personal preference :)

**Comment by thom-nic** [comment]
Based on [my HN comment](https://news.ycombinator.com/item?id=11212798) it seems a lot of people don't know about this trick.  I tend to think it doesn't alter the default behavior _too_ much since you still get linear history if you don't type anything before hitting `<up>`.  But fair enough if you don't want to add it.  

However since this seems to be not widely known (judging by the comment thread) it might be worth adding either as commented-out "enable this if you want it" options or maybe worth noting in the README?  Seems like something many people who have not already customized the heck out of their bashrc would appreciate. 

(it's also a default setting in oh-my-zsh.)

**Comment by mrzool** [comment]
That all sounds very reasonable. Maybe your suggestion would make a good sensible default after all.

**Comment by thom-nic** [comment]
Cool!  So I think if you want to keep it bash-sensible as a single bashrc file you would do these options as `bind` commands like so:

``` bash
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
```
